export const products = [
    { id: 1, 
      name: "HP Laptop", 
      price: 120.99,
      img:'/images/hpp.png', 
    },
    { id: 2, 
      name: "Mac", 
      price: 150.99,
      img:'/images/acss1.png', 
    },
    { id: 3, 
      name: "Tecno", 
      price: 50.99,
      img:'/images/acss2.png',
    },
    { id: 4, 
      name: "Infinix", 
      price: 20.99,
      img:'/images/dell1.png', 
    },
    { id: 5, 
      name: "Lenovo", 
      price: 100.99,
      img:'/images/ap2.png', 
    },
  ];